### ISSUE TITLE
Add more features 

### ISSUE THREAD

**Issue by mabed-fr** [Harkame/YggTorrentScraper#6]
Do you want add this feature :

- Select torrent language
- Select torrent subtitle

Its possible ?

Thank you :)

Mathieu

**Comment by Harkame** [comment]
Its just search options, I have add it in todolist (with search by category, etc) on dev branch, but before I will finish an big refacto on method search usage.

and what is torrent subtitle, is it "Description" field ?

**Comment by mabed-fr** [comment]
Yes its search options

My bad I don't have à field for subtiles..

thank you for your work!

**Comment by Harkame** [comment]
Added, make sure you are using yggtorrentscraper==1.2.3

I haven't test so much search by category, subcategory and fields so it can be a bit bugged.

Its not very easy to use, I will write better documentation in the future.

This example should work

``` python

import requests
from yggtorrentscraper import YggTorrentScraper

scraper = YggTorrentScraper(requests.session())

torrents_url = scraper.search(
    {
        "name": "walking dead",
        "category": "films_&_videos",
        "subcategory": "serie_tv",
        "options": {
            "langue": {"francais_(vff/truefrench)", "multi_(francais_inclus)"},
            "qualite": {"bluray_[full]"},
            "saison": {"serie_integrale"},
        },
    }
)
```

You can find all categories, subcategories and options here : https://github.com/Harkame/YggTorrentScraper/blob/master/yggtorrentscraper/categories.py
